name: Code Coverage Gating

on:
  push:
    branches: [main, "AllenDemoPR"]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '7.x'  # Adjust the version to your project's needs

    - name: Install dependencies
      run: dotnet restore

    - name: Run tests with coverage
      run: dotnet test --collect:"XPlat Code Coverage"

    - name: Generate coverage report
      run: dotnet tool install --global dotnet-reportgenerator-globaltool

    
    - name: Generate HTML report
      run: reportgenerator -reports:./TestResults/**/*.xml -targetdir:./coverage -reporttypes:Html

    - name: Check code coverage
      id: coverage
      run: |
        coverage=$(grep -Po 'line-rate="\K[0-9.]*' ./coverage/index.html | head -1)
        coverage=${coverage:-0}
        echo "Code coverage is $coverage"
        echo "::set-output name=coverage::$coverage"
    
    - name: Enforce code coverage
      if: steps.coverage.outputs.coverage < 80
      run: exit 1
