name: Code Coverage Gating

on:
  push:
    branches: [main, "AllenDemoPR"]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '7.x'  # Adjust the version to your project's needs

    - name: Install dependencies
      run: dotnet restore

    - name: Build solution
      run: dotnet build --configuration Release --no-restore

    - name: Run tests with coverage
      run: dotnet test --configuration Release --no-build --collect:"XPlat Code Coverage"

    - name: Generate HTML report
      run: |
        dotnet tool install --global dotnet-reportgenerator-globaltool
        reportgenerator -reports:**/TestResults/**/*.xml -targetdir:coveragereport -reporttypes:Html

    - name: Check code coverage
      id: coverage
      run: |
        coverage=$(grep -Po 'Line coverage:"\K[0-9.]*' ./coveragereport/index.html | head -1)
        coverage=${coverage:-0}
        echo "Code coverage is $coverage"
        echo "::set-output name=coverage::$coverage"
    
    - name: Enforce code coverage
      if: steps.coverage.outputs.coverage < 80
      run: exit 1
