name: Code Coverage Gating

on:
  push:
    branches: [main, "AllenDemoPR"]

jobs:
  check-coverage:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Fetch HTML Coverage Report
      run: curl -o coverage.html https://cisco-allenwang.github.io/APEX-UiPath-Code-Review-POC/

    - name: Parse Line Coverage
      id: coverage
      run: |
        line_coverage=$(grep -oP 'Line Coverage:\s*\K\d+\.\d+' index.html)
        echo "Line Coverage is $line_coverage%"
        echo "::set-output name=line_coverage::$line_coverage"

    - name: Enforce Line Coverage
      if: steps.coverage.outputs.line_coverage < 80
      run: |
        echo "Code coverage is below the threshold of 80%"
        exit 1
 
